export class HtmlHelper {
    static get tags() {
        return {
            a: 'a',
            abbr: 'abbr',
            acronym: 'acronym',
            address: 'address',
            applet: 'applet',
            area: 'area',
            article: 'article',
            aside: 'aside',
            audio: 'audio',
            b: 'b',
            base: 'base',
            baseFont: 'basefont',
            bdi: 'bdi',
            bdo: 'bdo',
            big: 'big',
            blockQuote: 'blockquote',
            body: 'body',
            br: 'br',
            button: 'button',
            canvas: 'canvas',
            caption: 'caption',
            center: 'center',
            cite: 'cite',
            code: 'code',
            col: 'col',
            colGroup: 'colgroup',
            command: 'command',
            dataList: 'datalist',
            dd: 'dd',
            del: 'del',
            details: 'details',
            dfn: 'dfn',
            dir: 'dir',
            div: 'div',
            dl: 'dl',
            dt: 'dt',
            em: 'em',
            embed: 'embed',
            fieldSet: 'fieldset',
            figCaption: 'figcaption',
            figure: 'figure',
            font: 'font',
            footer: 'footer',
            form: 'form',
            frame: 'frame',
            frameSet: 'frameset',
            h1: 'h1',
            h2: 'h2',
            h3: 'h3',
            h4: 'h4',
            h5: 'h5',
            h6: 'h6',
            head: 'head',
            header: 'header',
            hGroup: 'hgroup',
            hr: 'hr',
            html: 'html',
            i: 'i',
            iFrame: 'iframe',
            img: 'img',
            input: 'input',
            ins: 'ins',
            kbd: 'kbd',
            keyGen: 'keygen',
            label: 'label',
            legend: 'legend',
            li: 'li',
            link: 'link',
            map: 'map',
            mark: 'mark',
            menu: 'menu',
            meta: 'meta',
            meter: 'meter',
            nav: 'nav',
            noFrames: 'noframes',
            noScript: 'noscript',
            object: 'object',
            ol: 'ol',
            optGroup: 'optgroup',
            option: 'option',
            output: 'output',
            p: 'p',
            param: 'param',
            pre: 'pre',
            progress: 'progress',
            q: 'q',
            rp: 'rp',
            rt: 'rt',
            ruby: 'ruby',
            s: 's',
            sAmp: 'samp',
            script: 'script',
            section: 'section',
            select: 'select',
            small: 'small',
            source: 'source',
            span: 'span',
            strike: 'strike',
            strong: 'strong',
            style: 'style',
            sub: 'sub',
            summary: 'summary',
            sup: 'sup',
            table: 'table',
            tBody: 'tbody',
            td: 'td',
            textArea: 'textarea',
            tFoot: 'tfoot',
            th: 'th',
            tHead: 'thead',
            time: 'time',
            title: 'title',
            tr: 'tr',
            track: 'track',
            tt: 'tt',
            u: 'u',
            ul: 'ul',
            var: 'var',
            video: 'video',
            wbr: 'wbr',
            gridTemplateRender: 'grid-template-render',
        };
    }

    public static get additionalAttributes() {
        return {
            ngRepeat: 'ng-repeat',
            ariaExpanded: 'aria-expanded',
            ariaDescribedby: 'aria-describedby',
            nghref: 'ng-href',
            uibTooltip: 'uib-tooltip',
            dataDatatablePgVal: 'data-datatable-pg-val',
            dataId: 'data-id',
            role: 'role',
            entity: 'entity',
            fill: 'fill',
            textDecoration: 'text-decoration'
        };
    }

    public static get xpathExpressions() {
        return {
            following: 'following',
            ancestor: 'ancestor',
            ancestorOrSelf: 'ancestor-or-self',
            descendant: 'descendant',
            descendantOrSelf: 'descendant-or-self',
            followingSibling: 'following-sibling',
            preceding: 'preceding',
            precedingSibling: 'preceding-sibling',
            parent: 'parent',
        };
    }

    public static get types() {
        return {
            button: 'button',
            checkbox: 'checkbox',
            color: 'color',
            date: 'date',
            datetimeLocal: 'datetime-local',
            email: 'email',
            file: 'file',
            hidden: 'hidden',
            image: 'image',
            month: 'month',
            number: 'number',
            password: 'password',
            radio: 'radio',
            range: 'range',
            reset: 'reset',
            search: 'search',
            submit: 'submit',
            tel: 'tel',
            text: 'text',
            time: 'time',
            url: 'url',
            week: 'week',
        };
    }

    static readonly attributes: {
        accept: string;
        acceptCharset: string;
        accessKey: string;
        action: string;
        align: string;
        alt: string;
        async: string;
        autoComplete: string;
        autoFocus: string;
        autoPlay: string;
        bgColor: string;
        border: string;
        buffered: string;
        challenge: string;
        charset: string;
        checked: string;
        cite: string;
        class: string;
        code: string;
        codebase: string;
        color: string;
        cols: string;
        colspan: string;
        content: string;
        contentEditable: string;
        contextMenu: string;
        controls: string;
        coords: string;
        crossOrigin: string;
        data: string;
        datetime: string;
        defaultt: string;
        defer: string;
        dir: string;
        dirName: string;
        disabled: string;
        download: string;
        draggable: string;
        dropZone: string;
        enctype: string;
        for: string;
        form: string;
        formControlName: string;
        formAction: string;
        headers: string;
        height: string;
        hidden: string;
        high: string;
        href: string;
        hrefLang: string;
        httpEquiv: string;
        icon: string;
        id: string;
        integrity: string;
        isMap: string;
        itemProp: string;
        keyType: string;
        kind: string;
        label: string;
        lang: string;
        language: string;
        list: string;
        loop: string;
        low: string;
        manifest: string;
        max: string;
        maxLength: string;
        minLength: string;
        media: string;
        method: string;
        min: string;
        multiple: string;
        muted: string;
        name: string;
        novalidate: string;
        open: string;
        optimum: string;
        pattern: string;
        ping: string;
        placeholder: string;
        poster: string;
        preload: string;
        radioGroup: string;
        readonly: string;
        rel: string;
        required: string;
        reversed: string;
        rows: string;
        rowSpan: string;
        sandbox: string;
        scope: string;
        scoped: string;
        seamless: string;
        selected: string;
        shape: string;
        size: string;
        sizes: string;
        slot: string;
        span: string;
        spellCheck: string;
        src: string;
        srcDoc: string;
        srcLang: string;
        srcset: string;
        start: string;
        step: string;
        style: string;
        summary: string;
        tabIndex: string;
        target: string;
        title: string;
        type: string;
        useMap: string;
        value: string;
        width: string;
        wrap: string;
    };
}
